#!/bin/bash
#
# setup.sh — WeChat Gateway Pool Manager 一键部署脚本
#
# 用法:
#   bash setup.sh                          # 默认配置
#   bash setup.sh --total 50 --hot-pool 3  # 按机器配置自定义
#   bash setup.sh --help                   # 看全部参数
#

set -euo pipefail

# ── 默认值 ──────────────────────────────────────────────────────────────
TOTAL=100
HOT_POOL=5
MAX_BOUND=80
PORT=8765
PREFIX="weixin-"
HOST="0.0.0.0"

# ── 参数解析 ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --total)       TOTAL="$2";    shift 2 ;;
    --hot-pool)    HOT_POOL="$2"; shift 2 ;;
    --max-bound)   MAX_BOUND="$2"; shift 2 ;;
    --port)        PORT="$2";     shift 2 ;;
    --prefix)      PREFIX="$2";   shift 2 ;;
    --host)        HOST="$2";     shift 2 ;;
    --help|-h)
      echo "用法: bash setup.sh [选项]"
      echo ""
      echo "选项:"
      echo "  --total NUM    预创建 profile 总数（默认 100）"
      echo "  --hot-pool NUM 热池常驻槽位数（默认 5）"
      echo "  --max-bound NUM 最大同时运行 gateway 数（默认 80）"
      echo "  --port NUM     API 端口（默认 8765）"
      echo "  --prefix STR   profile 名前缀（默认 weixin-）"
      echo "  --host STR     监听地址（默认 0.0.0.0）"
      echo ""
      echo "示例:"
      echo "  bash setup.sh --total 30 --hot-pool 3 --max-bound 15"
      echo "  bash setup.sh --total 100 --hot-pool 5 --max-bound 80"
      exit 0
      ;;
    *)
      echo "未知参数: $1"
      echo "使用 --help 查看帮助"
      exit 1
      ;;
  esac
done

echo "══════════════════════════════════════════════════"
echo "   WeChat Gateway Pool Manager — 部署"
echo "══════════════════════════════════════════════════"
echo ""
echo "配置:"
echo "  total_profiles: $TOTAL"
echo "  hot_pool_size:  $HOT_POOL"
echo "  max_bound:      $MAX_BOUND"
echo "  port:           $PORT"
echo "  prefix:         $PREFIX"
echo ""

# ── 检查 Hermes ──────────────────────────────────────────────────────────
if ! command -v hermes &>/dev/null; then
  echo "[1/6] ? Hermes 未找到，开始安装..."
  curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash
else
  echo "[1/6] ? Hermes 已安装"
fi

# ── 安装 Python 依赖 ─────────────────────────────────────────────────────
echo "[2/6] ? 安装 Python 依赖..."
HERMES_VENV="$HOME/.hermes/hermes-agent/venv"
if [ -f "$HERMES_VENV/bin/pip" ]; then
  PIP="$HERMES_VENV/bin/pip"
else
  PIP="pip3"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

if [ -f "$PROJECT_DIR/requirements.txt" ]; then
  "$PIP" install -r "$PROJECT_DIR/requirements.txt" -q
fi

# ── 创建目录结构 + 配置 ──────────────────────────────────────────────────
echo "[3/6] ? 创建目录结构..."
mkdir -p "$HOME/.hermes/wechat-pool/logs"
mkdir -p "$HOME/.hermes/wechat-pool/pool_manager"
mkdir -p "$HOME/.hermes/wechat-pool/static"

# 复制代码
cp -r "$PROJECT_DIR/pool_manager/"* "$HOME/.hermes/wechat-pool/pool_manager/"
cp -r "$PROJECT_DIR/static/"* "$HOME/.hermes/wechat-pool/static/"

# 生成配置文件（用传入的参数覆盖默认配置）
cat > "$HOME/.hermes/wechat-pool/config.yaml" << CONFIGEOF
# WeChat Gateway Pool Manager Configuration
# Generated by setup.sh

pool:
  total_profiles: $TOTAL
  hot_pool_size: $HOT_POOL
  max_bound_gateways: $MAX_BOUND
  profile_prefix: "$PREFIX"
  max_qr_refresh: 3

gateway:
  idle_timeout_minutes: 1440
  restart_on_crash: true
  max_restart_attempts: 3
  restart_delay_seconds: 10
  health_check_interval: 60

frontend:
  api_port: $PORT
  qr_refresh_seconds: 45
  host: "$HOST"
  public_url: ""

logging:
  level: INFO
  dir: "$HOME/.hermes/wechat-pool/logs/"
  retain_days: 7
  stats_window_hours: 168

ilink:
  base_url: "https://ilinkai.weixin.qq.com"
  qr_timeout_seconds: 480
  qr_poll_interval: 1
CONFIGEOF
echo "  目录结构 + 配置文件创建完成"

# ── 复制并安装 systemd 服务 ─────────────────────────────────────────────
echo "[4/6] ? 部署 systemd 服务..."
SYSTEMD_DIR="$HOME/.config/systemd/user"
mkdir -p "$SYSTEMD_DIR"

# 使用 %h 变量保证跨机器兼容
cat > "$SYSTEMD_DIR/hermes-pool.service" << SERVICEEOF
[Unit]
Description=Hermes WeChat Gateway Pool Manager
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=%h/.hermes/hermes-agent/venv/bin/python \\
  -c "import sys; sys.path.insert(0, '%h/.hermes/wechat-pool/'); from pool_manager.service import main; main()" \\
  --config %h/.hermes/wechat-pool/config.yaml
WorkingDirectory=%h/.hermes/wechat-pool/
Environment="PATH=%h/.hermes/hermes-agent/venv/bin:%h/.hermes/node/bin:%h/.local/bin:%h/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Environment="VIRTUAL_ENV=%h/.hermes/hermes-agent/venv"
Restart=on-failure
RestartSec=10
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=90
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
SERVICEEOF

cp "$PROJECT_DIR/systemd/hermes-gateway@.service" "$SYSTEMD_DIR/"

systemctl --user daemon-reload
echo "  systemd 配置已加载"

# ── 批量创建 profile（可选，已存在的跳过） ──────────────────────────────
echo "[5/6] ? 创建 profile..."
python3 "$PROJECT_DIR/scripts/create_profiles.py" \
  --count "$TOTAL" --prefix "$PREFIX"

# ── 启动 Pool Manager ────────────────────────────────────────────────────
echo "[6/6] ? 启动 Pool Manager..."
systemctl --user enable hermes-pool 2>/dev/null || true
systemctl --user restart hermes-pool

echo ""
echo "══════════════════════════════════════════════════"
echo "   ✅ 部署完成！"
echo ""
echo "   Pool Manager:  http://$HOST:$PORT"
echo "   前端页面:      http://$HOST:$PORT"
echo "   健康检查:      http://$HOST:$PORT/health"
echo ""
echo "   查看日志:"
echo "     journalctl --user -u hermes-pool -f"
echo "     tail -f $HOME/.hermes/wechat-pool/logs/pool_manager.log"
echo ""
echo "   ⚠️ 如果端口 $PORT 被占用，用 --port 指定其他端口"
echo "══════════════════════════════════════════════════"